---
# tasks file for nginxRole
- name: install nginx
  command: amazon-linux-extras install nginx1 -y
  #yum: pkg="{{ pkg_name }}" state=present
  notify: start nginx
- template:
          src: versionOS.j2
          dest: ./fileNginx.txt
